### ISSUE TITLE
Out of date documentation on --auto-req options in readme

### ISSUE THREAD

**Issue by Will-Shanks** [cat-in-136/cargo-generate-rpm#101]
The readme suggests passing `--auto-req no` to disable the automatic dependency processing, however that doesn't work since "no" isn't an option in the `AutoReqMode` [enum](https://github.com/cat-in-136/cargo-generate-rpm/blob/ba851a3e08f881f050104f4ba48bae91bdf848d7/src/cli.rs#L106)
```
> cargo generate-rpm --auto-req no
error: invalid value 'no' for '--auto-req <AUTO_REQ>'
  [possible values: disabled, builtin, find-requires, /path/to/find-requires]

For more information, try '--help'.
```

Happy to submit a PR updating the docs s/no/disabled/ but adding an [alias](https://docs.rs/clap/latest/clap/struct.Arg.html#method.aliases) of no is also an option.

**Comment by cat-in-136** [comment]
Thank you for reporting, @Will-Shanks . It is a degrade of #82 rather than out-of document. I prefer to add an alias.

You can submit a PR to add the alias.
