### ISSUE TITLE
 rpmlib(PayloadIsZstd) = 5.4.18-1 is needed

### ISSUE THREAD

**Issue by dongbin86** [cat-in-136/cargo-generate-rpm#104]
hi, I successfully created a rpm package ,but an error occured when I install that rpm package in centos7

error: Failed dependencies:
        rpmlib(PayloadIsZstd) = 5.4.18-1 is needed by polly-agent-0:0.1.0-1.x86_64

how to fix this problem ?

**Comment by cat-in-136** [comment]
Set compression type as written in README.md.

> For the legacy system (e.g. centos7), specify legacy compress type explicitly e.g. `--payload-compress none`.

**Comment by cat-in-136** [comment]
duplicate of #30
