### ISSUE TITLE
Versions above 0.14.0 i.e. 0.14.1 and 0.15.0 dont work at all

### ISSUE THREAD

**Issue by aegoroff** [cat-in-136/cargo-generate-rpm#116]
just run cargo generate-rpm ... without any changes and i got `error: The following required argument was not provided: auto_req`

auto_req not set in command line or in Cargo.toml file.

Nothing helps i.e. explicit setting this option from command line or in Cargo.toml file

**Comment by cat-in-136** [comment]
duplicated with #114
