### ISSUE TITLE
lib is needed by rpm install but it's already presented

### ISSUE THREAD

**Issue by M5135213521asd3** [cat-in-136/cargo-generate-rpm#122]
Hello, I have created rpm package by  cargo generate-rpm. When I try to install it I got:

```
$ rpm -ivh generate-rpm/api-0.1.0-1.x86_64.rpm
error: Failed dependencies:
        libcassandra.so.2()(64bit) is needed by api-0:0.1.0-1.x86_64
```

but cargo run command working without issue and library is presented on the system:
```
$ ldd release/api
       ...
        libcassandra.so.2 => /usr/local/lib64/libcassandra.so.2 (0x00007f87fe600000)
      ...
```

--auto-req disabled will disable this check which solve the issue, but I will rather keep it enabled to warn me when library is missing.

**Comment by cat-in-136** [comment]
In advance, please check  `rpm -q --whatprovides 'libcassandra.so.2()(64bit)'`.
If the output say no package provides libcassandra, your rpm file would not work. libcassandra shall be also managed by RPM, which is a specification of the RPM package manager itself.

**Comment by M5135213521asd3** [comment]
it is working fine once library is installed by rpm...
probaby can be closed...
thankls
