### ISSUE TITLE
UPX compressed binary gives RPM with no requires - can't install RPM

### ISSUE THREAD

**Issue by michaelst0** [cat-in-136/cargo-generate-rpm#123]
I have a rust binary that I `cross build` to get an aarch64 binary. I then `cargo generate-rpm` for this binary. Executing `rpm -qpR foo-0.1.0-1.aarch64.rpm` gives
```
# rpm -qpR ./foo-0.1.0-1.aarch64.rpm
/bin/sh
ld-linux-aarch64.so.1()(64bit)
ld-linux-aarch64.so.1(GLIBC_2.17)(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.18)(64bit)
libc.so.6(GLIBC_2.25)(64bit)
libc.so.6(GLIBC_2.28)(64bit)
libc.so.6(GLIBC_2.29)(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.17)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgcc_s.so.1(GCC_3.3)(64bit)
libgcc_s.so.1(GCC_4.2.0)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.17)(64bit)
libm.so.6(GLIBC_2.29)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.17)(64bit)
rtld(GNU_HASH)
rpmlib(CompressedFileNames) = 3.0.4-1
rpmlib(FileDigests) = 4.6.0-1
rpmlib(PayloadFilesHavePrefix) = 4.0-1
rpmlib(PayloadIsZstd) = 5.4.18-1
```
And I can install the RPM using `rpm-ostree install ./foo-0.1.0-1.aarch64.rpm`. Great!

Now, when I use [UPX](https://upx.github.io/) to compress the binary and perform the same steps to generate an RPM, I get the following from `rpm -qpR ./foo-0.1.0-1.aarch64.rpm`
```
# rpm -qpR ./foo-0.1.0-1.aarch64.rpm
/bin/sh

rpmlib(CompressedFileNames) = 3.0.4-1
rpmlib(FileDigests) = 4.6.0-1
rpmlib(PayloadFilesHavePrefix) = 4.0-1
rpmlib(PayloadIsZstd) = 5.4.18-1
```
**Note the empty line above**. Now when I try to install the RPM, I get an error message from `rpm-ostree`
```
# rpm-ostree install ./foo-0.1.0-1.aarch64.rpm
Checking out tree 845fdcc... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2024-03-12T11:45:42Z solvables: 3
rpm-md repo 'updates' (cached); generated: 2024-11-07T01:41:00Z solvables: 27389
rpm-md repo 'fedora' (cached); generated: 2024-04-14T18:51:04Z solvables: 65497
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides  needed by ./foo-0.1.0-1.aarch64.rpm from @commandline
```
Looks like it's trying to resolve the empty line ` ` as a dependency, which it can't.

**Comment by cat-in-136** [comment]
As with the original rpm, automatic resolution of dependencies is done using ldd, so I think it is impossible to resolve dependency UPX compression binary in usual way.

Note that if you have a binary dependent resolution method, you can replace the resolution process.

https://github.com/cat-in-136/cargo-generate-rpm#packagemetadatagenerate-rpmrequiresobsoletesconflictsprovidesrecommendssupplementssuggestsenhances-options

**Comment by michaelst0** [comment]
Adding `auto-req = "no"` works.  
```
[package.metadata.generate-rpm]
auto-req = "no"
```
Thanks @cat-in-136.
