### ISSUE TITLE
Release Should Accept Strings

### ISSUE THREAD

**Issue by JamesMc86** [cat-in-136/cargo-generate-rpm#16]
In the read-me it states that release takes a strings but when I tried this it only takes numerics.

It should use strings to allow for pre-release versions etc. I'll create a PR for this now hopefully.

**Comment by JamesMc86** [comment]
Haha and as I sit to try this - I see that actually it is an rpm-rs issue. Will file this with them as well.

**Comment by Richterrettich** [comment]
Hi,
I've released a new version of rpm-rs which allows you to use strings for `release`.
