### ISSUE TITLE
Install different files for different targets

### ISSUE THREAD

**Issue by ximon18** [cat-in-136/cargo-generate-rpm#18]
Hi,

How would I use `cargo generate-rpm` to install a different systemd service file on an older RHEL/CentOS release than on a newer release? For comparison, with `cargo deb` I used the "variants" support in Cargo.toml to define different assets to install in different "variants".

Thanks,

Ximon

**Comment by cat-in-136** [comment]
Currently no plan to introduce like of variants

**Comment by ximon18** [comment]
To work around this I think I'm going to have to do something ugly like search and replace the Cargo.toml file or have two almost identical Cargo.toml files or change the actual file that exists at the location pointed to by the assets or include two service units but only activate one of them. Do you have a better suggestion on how I can solve this? For example on CentOS 7 systemd doesn't understand settings in the service unit file that are understood by systemd on CentOS 8 so I have to use different service unit files. I really don't want the package to include two different units and only activate one of them.

**Comment by cat-in-136** [comment]
@ximon18 I believe that it is resolved by #36.

**Comment by ximon18** [comment]
Thanks, I'm going to investigate if indeed I can address this using the new metadata overwrite capabilities of cargo-generate-rpm! I'll re-open this issue if I find a problem when trying to do that.
