### ISSUE TITLE
broken RPM generated when mode specified

### ISSUE THREAD

**Issue by cat-in-136** [cat-in-136/cargo-generate-rpm#2]
Broken RPM which `rpm -ivh` cannot unpack files and install:

```
error: unpacking of archive failed on file /usr/bin/XXX;XXXXXXXX: cpio: Unknown file type
```

**Comment by cat-in-136** [comment]
The argument of https://docs.rs/rpm-rs/0.6.0/rpm/struct.RPMFileOptionsBuilder.html#method.mode shall be same value as `st_mode` and the file type bit field is mandatory.

The file type bit field description is written in linux programmer's manual (man) of `inode(7)`:

>            S_IFMT     0170000   bit mask for the file type bit field
> 
>            S_IFSOCK   0140000   socket
>            S_IFLNK    0120000   symbolic link
>            S_IFREG    0100000   regular file
>            S_IFBLK    0060000   block device
>            S_IFDIR    0040000   directory
>            S_IFCHR    0020000   character device
>            S_IFIFO    0010000   FIFO

For example, `0o0100755` should be set to typical executable file.

**Comment by drahnr** [comment]
Could you file an upstream bug to rpm-rs about this. That'd be much appreciated!
