### ISSUE TITLE
rpmlint warnings

### ISSUE THREAD

**Issue by ximon18** [cat-in-136/cargo-generate-rpm#20]
Hi,

When I run `rpmlint` on my generated RPM I get some warnings which I think I have no control over as they refer to missing spec fields that are not generated by `cargo-generate-rpm`, e.g.:

- `routinator.x86_64: W: manpage-not-compressed gz /usr/share/man/man1/routinator.1`

It's a bit ugly to either store the man page compressed in my Git repo. I could compress it before invoking `cargo generate-rpm`, but as `cargo-generate-rpm` is aware of "doc" assets perhaps it could compress it for me?

- `routinator.x86_64: E: no-buildhost-tag`
- `routinator.x86_64: E: no-changelogname-tag`
- `routinator.x86_64: W: no-url-tag`

Unless I am mistaken I see no way to provide these via the `Cargo.toml` syntax supported by `cargo-generate-rpm`.

- `routinator.x86_64: E: no-binary`

Do you have any idea why even though I have binary assets installed to `/usr/bin/` it complains that I do not have a binary?

- `routinator.x86_64: W: conffile-without-noreplace-flag /etc/routinator/routinator.conf`

I assume this refers to some setting that I have no control over?

Thanks,

Ximon

**Comment by cat-in-136** [comment]
As you know, my app depends rpm-rs. rpm-rs does not have full feature of rpm. To support all features, we need to develop rpm-rs and cargo-generate-rpm.

These are features that should be supported, but there are no plans to provide them at this time. Because I did not have enough time to develop these as of now.

FYI: pull request is welcome!

**Comment by ximon18** [comment]
Hi,

I would be happy to provide pull requests, I did the same for cargo deb.

Before doing so I wanted first to be sure I am not missing something either with what makes sense in the RPM world (as I have more experience with Debian packaging but even then I am primarily a package consumer, not a package creator) or that I misunderstood or simply missed a feature of this tool.

For example, the answer to the question in another issue about multi-line pre/post scripts showed that, while not immediately obvious to me, there is a relatively clean way to do what I wanted. In that case maybe a README PR would be an idea?

For anything where a PR would be acceptable I am happy to contribute, either here or to the underlying rpm-rs crate.

It might be early next week before I am able to work on a PR, if I can do so earlier I will.

If there are any other issues  where a PR would be welcome, please let me know and I'll see what I can to do contribute.

Ximon

**Comment by ximon18** [comment]
Oh dear, I see that I said I would try to do a PR... a very long time ago! Clearly that didn't happen and I should be more careful what I promise! Sorry...

**Comment by ximon18** [comment]
So, I'm running in to this issue again and see that I already reported it and said already that I would solve it hah! Typical. Let me try and do something about it this time.

**Comment by ximon18** [comment]
I've also just commented on https://github.com/rpm-rs/rpm/issues/26#issuecomment-1325573698 regarding this issue.

**Comment by drahnr** [comment]
Hey :wave: 

https://github.com/rpms-rs/rpm is a group driving the original `rpm-rs` forward, which is yet to be published (ETA next few days). 

If there are any features missing, we'd very much appreciate the feedback to incorporate the features required :)

**Comment by cat-in-136** [comment]
It is out-of-scope as of now. Because rpm-rs does not build _valid_ rpm files.

When rpm-rs is able to build _valid_ rpm files, it should be cared.
