### ISSUE TITLE
Cannot publish to crates.io by git+rev dependency of PR #23

### ISSUE THREAD

**Issue by cat-in-136** [cat-in-136/cargo-generate-rpm#24]
In PR #23 and issue #21, git+rev dependency was added to Cargo.toml but it is not acceptable for publishing to crates.io. 

```console
$ cargo publish --dry-run
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `rpm-rs` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.

```

**Comment by cat-in-136** [comment]
It seems that there is no way except for creating and publishing a _forked_ rpm-rs package.

https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
> If you publish the crates in the workspace to crates.io, each crate in the workspace will need to be published separately. The cargo publish command does not have an --all flag or a -p flag, so you must change to each crate’s directory and run cargo publish on each crate in the workspace to publish the crates.

**Comment by ximon18** [comment]
Does the `rpm-rs` project not plan to do a release to crates.io themselves?

**Comment by ximon18** [comment]
Have you contacted the owners of the `rpm-rs` project about this issue?

Could a horrible hack be to temporarily use `cargo vendor` to pull the unrelease rpm-rs sources (and everything else...) into your project and `cargo publish` that?
