### ISSUE TITLE
RPM install fails with cpio bad magic

### ISSUE THREAD

**Issue by jtk18** [cat-in-136/cargo-generate-rpm#28]
Steps to reproduce on a centos 7 machine with Rust installed already:

1. `git clone https://github.com/cat-in-136/cargo-generate-rpm.git; cd cargo-generate-rpm`
2. `cargo install cargo-generate-rpm`
3. `cargo build --release; strip -s target/release/cargo-generate-rpm`
4. `cargo generate-rpm`
5. `rpm -i target/generate-rpm/cargo-generate-rpm-0.5.0-1.x86_64.rpm`

Result:

```
error: unpacking of archive failed: cpio: Bad magic
error: cargo-generate-rpm-0:0.5.0-1.x86_64: install failed
```

I'm fairly certain it's the rpm-rs crate, of course, but I thought I'd report it to you first to see if you had any ideas? Thank you very much!

**Comment by cat-in-136** [comment]
Could you please try to run cargo generate-rpm--payload-compress none?
