### ISSUE TITLE
do you plan to support multiple config?

### ISSUE THREAD

**Issue by jm-observer** [cat-in-136/cargo-generate-rpm#31]
sometime a package has some bins, so it exists demand to config each bin.do you plan to support it or mind other submit pr. the confis like:
```
[package.metadata.generate-rpm.A]
assets = [
    { source = "target/release/a", dest = "/usr/local/bin/a", mode = "0755"},
[package.metadata.generate-rpm.B]
assets = [
    { source = "target/release/b", dest = "/usr/local/bin/b", mode = "0755"},
```

**Comment by cat-in-136** [comment]
Why don't you use `--target` option or `CARGO_BUILD_TARGET` if you want to create rpm files for different arch binaries?

**Comment by jm-observer** [comment]
Modify the configuration file first and then create it?Do I want to keep the configuration files for each RPM that are now supported?

**Comment by cat-in-136** [comment]
I assume that your examples indicates cross compile (glibc native and musl cross compile). Refer https://github.com/cat-in-136/cargo-generate-rpm/blob/master/README.md#cross-compilation for cross compilation.

If you do not intended cross compile, the answer would be no. Currently , no plan to create different (sub)packages, e.g. foobar-utils and foobar-utils-baz.

**Comment by jm-observer** [comment]
ok
