### ISSUE TITLE
Would you like the `cargo-rpm` crate?

### ISSUE THREAD

**Issue by tony-iqlusion** [cat-in-136/cargo-generate-rpm#33]
The `cargo-rpm` crate is unmaintained: https://github.com/iqlusioninc/cargo-rpm/issues/96

If you'd like, we could give you the `cargo-rpm` crate name and you could potentially publish future releases of `cargo-generate-rpm` under that.

**Comment by cat-in-136** [comment]
@tony-iqlusion , Thank you for the proposal. But my answer is no.

`cargo-generate-rpm` has different approach than `cargo-rpm` --- do without `rpmbuild`. I thought it was better not to use the cargo-rpm crate name for my app to avoid user misunderstanding and compatibility issues.
