### ISSUE TITLE
No 0.7.0 release tag but 0.7.0 exists on crates.io?

### ISSUE THREAD

**Issue by ximon18** [cat-in-136/cargo-generate-rpm#38]
Hi,

The latest release tag here is 0.6.0 yet crates.io has 0.7.0.

Shouldn't there be a release tag and release notes here for 0.7.0 if that was an official release?

Thanks,

Ximon

**Comment by cat-in-136** [comment]
Thank you for reporting . It has been resolved. https://github.com/cat-in-136/cargo-generate-rpm/releases/tag/v0.7.0
