### ISSUE TITLE
Support for rpm file which does not have a dependency on /bin/sh

### ISSUE THREAD

**Issue by tofay** [cat-in-136/cargo-generate-rpm#39]
All RPMs generated by cargo-generate-rpm require `/bin/sh`. 

This seems unnecessary, as Rust binaries don't universally require a shell. In my case I'm trying to build distroless-like containers from RPMs generated by cargo-generate-rpm, and this is causing a shell and it's dependencies to be pulled in unnecessarily.

This behaviour comes from by rpm-rs, which appears to not be maintained at present: https://github.com/Richterrettich/rpm-rs/issues/54. I've raised a PR to https://github.com/rpm-rs/rpm-rs/pull/7 - which is a community fork that isn't yet publishing to crates-io.

**Comment by cat-in-136** [comment]
rpm-rs/rpm#7 has been merged to the fork of rpm-rs, which  is a maintained-but-not-published-for-a-long-time community fork.

They do not care about backward compatibility. So, it is necessary to do following tasks on switching rpm-rs/rpm:
* add `/bin/sh` to dependency automatically, which is usually necessary
* add functionality to omit `/bin/sh` in dependency
