### ISSUE TITLE
Release Binaries

### ISSUE THREAD

**Issue by kallisti-dev** [cat-in-136/cargo-generate-rpm#58]
Hello! I'm using cargo-generate-rpm in the release workflow for [cloudtruth/cloudtruth-cli](https://github.com/cloudtruth/cloudtruth-cli). I've been able to speed up the build considerably by downloading prebuilt binaries of cross and cargo-deb rather than building from source, but I am unable to do the same with cargo-generate-rpm because there are no binaries available  it would be nice to be able to quickly download a release binary with `cargo-binstall` or `cargo-quickinstall` rather than compiling from source each build.

**Comment by cat-in-136** [comment]
Thank you for filing this issue. But, it should be requested to cargo-quickinstall project team.

For example, cargo-quickinstall cargo-deb seems to download from https://github.com/cargo-bins/cargo-quickinstall/releases?q=cargo-deb&expanded=true It seems that `cargo-quickinstall cargo-deb` is downloaded from .
