### ISSUE TITLE
Support for `summary` silently dropped

### ISSUE THREAD

**Issue by ximon18** [cat-in-136/cargo-generate-rpm#69]
The [README](https://github.com/cat-in-136/cargo-generate-rpm/blob/master/README.md?plain=1#L43) still says:

> summary: the package summary/description. If not present, package.description is used.

However, PR #46 removed support for this and was included in release [v0.9.0](https://github.com/cat-in-136/cargo-generate-rpm/releases/tag/v0.9.0), but no mention of this was made in the release notes and the README was not updated.

Worse, using `summary` doesn't cause an error or warning, it just doesn't have the desired effect.

I only found this because `rpmlint` complains about my description being too long even though I set `summary` to a shorter text.

**Comment by ximon18** [comment]
Also, unless I am doing something wrong, it seems that setting `[package.metadata.generate-rpm].description` does not override `[package].description`.

**Comment by cat-in-136** [comment]
Oh, it is just a degrade bug caused by typo.

**Comment by ximon18** [comment]
Thanks @cat-in-136 for the quick response!
