### ISSUE TITLE
Support for `license-file`

### ISSUE THREAD

**Issue by dilawar** [cat-in-136/cargo-generate-rpm#72]
`Cargo.toml` supports https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields field. `cargo-deb` also supports the `license-file` field. It would be nice if we also supported `license-file` field. 

Happy to send MR.

**Comment by cat-in-136** [comment]
In rpm spec file, `License` tag is not expected to be used for the installed file.

**Comment by dilawar** [comment]
I am confused about this. I use Open Build Service to build packages and they  https://en.opensuse.org/openSUSE:Specfile_guidelines#License_files. They have `%license` in the spec file. Looks like this is supported since rpm >= 4.11. 

As you mentioned about the `License` field, only an `str` value is supported (from https://rpm-software-management.github.io/rpm/manual/spec.html).

![image](https://user-images.githubusercontent.com/895681/229271932-18ea65c6-c5e8-4fca-88b8-2da10e55546a.png)

I think I confused two different things here: `License` field and `%license` macro!
