### ISSUE TITLE
Script parameters should accept path to files, not script intself

### ISSUE THREAD

**Issue by newpavlov** [cat-in-136/cargo-generate-rpm#86]
It's weird to have shell scripts inside Cargo.toml, especially considering that sometimes they can be quite complex.

**Comment by jtk18** [comment]
You can specify a path like this:

`post_install_script = "/path/to/script.sh \"$@\""`

**Comment by newpavlov** [comment]
Does it mean that the script should be included into the package as an asset?

**Comment by jtk18** [comment]
Submitted https://github.com/cat-in-136/cargo-generate-rpm/pull/93 to attempt to resolve this.
