### ISSUE TITLE
Building rpm for `foo-bar` package means  `foo-bar/Cargo.toml` must exists?

### ISSUE THREAD

**Issue by dilawar** [cat-in-136/cargo-generate-rpm#99]
```
$ cargo generate-rpm -p foo-service
No such file or directory (os error 2): foo-service/Cargo.toml

```

In workspace's `Cargo.toml` file, `foo-service` is in `foo/service` folder i.e. `foo/service/Cargo.toml` exits. Its a bit non-standard location but I was expecting the tool to figure it out by itself. 

PS: Looks like it. Package name and its potential location is tightly linked. Package path is not being read from workspace `members` list.

```rust
    let config = if let Some(p) = &args.package {
        Config::new(Path::new(p), Some(Path::new("")), &extra_metadata)?
    } else {
        Config::new(Path::new(""), None, &extra_metadata)?
    };
```

**Comment by cat-in-136** [comment]
Such a non-standard location is not supported. (And I could not find how to use such a location.)

**Comment by georglauterbach** [comment]
I stumbled upon this, too, and it is in no way "non-standard". [`cargo-deb`](https://github.com/kornelski/cargo-deb) handles it perfectly fine for `.deb` packages, and [`cargo-wix`](https://github.com/volks73/cargo-wix) handles it perfectly fine for Windows packets.

Hence, this behavior is more than unexpected. As Cargo allows you to specify the folder name, it should be supported.
